# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactorKitPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactorKitPractice
  pod 'ReactorKit'
  pod 'RxCocoa'

  target 'ReactorKitPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactorKitPracticeUITests' do
    # Pods for testing
  end

end
